import type { Metadata } from "next";
import "./globals.scss";
import { ReduxProvider } from "./(sait)/providers";

export const metadata: Metadata = {
  title: "next.js NFT",
  description: "Generated by create next app",
};
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
